spring:
  profiles:
    active:
      prod
  servlet:
    encoding:
      charset: UTF-8
      enabled: false
      force: true

mybatis:
  mapper-locations: classpath:mapping/*.xml

# pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  config: classpath:logback-${spring.profiles.active}.xml