package com.cit.dmt.core.dao;

import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cit.dmt.core.model.CheckAssignment;
import com.github.pagehelper.Page;

public interface CheckAssignmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_assignment
     *
     * @mbg.generated Sun Jul 04 13:35:32 NZST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_assignment
     *
     * @mbg.generated Sun Jul 04 13:35:32 NZST 2021
     */
    int insert(CheckAssignment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_assignment
     *
     * @mbg.generated Sun Jul 04 13:35:32 NZST 2021
     */
    int insertSelective(CheckAssignment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_assignment
     *
     * @mbg.generated Sun Jul 04 13:35:32 NZST 2021
     */
    CheckAssignment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_assignment
     *
     * @mbg.generated Sun Jul 04 13:35:32 NZST 2021
     */
    int updateByPrimaryKeySelective(CheckAssignment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_assignment
     *
     * @mbg.generated Sun Jul 04 13:35:32 NZST 2021
     */
    int updateByPrimaryKey(CheckAssignment record);
    CheckAssignment selectByUserId(@Param("projectId") Long projectId, @Param("taskId") Long taskId, @Param("roundId") Long roundId, @Param("userId") Long userId, @Param("notThisId") Long notThisId);
    Integer getAssignedAmount(@Param("projectId") Long projectId, @Param("taskId") Long taskId, @Param("roundId") Long roundId);
    Page<CheckAssignment> selectPaged(Map<String, Object> criteria);
}