package com.cit.dmt.core.dao;

import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cit.dmt.core.model.CheckRound;
import com.github.pagehelper.Page;

public interface CheckRoundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_round
     *
     * @mbg.generated Sun Jul 04 13:35:32 NZST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_round
     *
     * @mbg.generated Sun Jul 04 13:35:32 NZST 2021
     */
    int insert(CheckRound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_round
     *
     * @mbg.generated Sun Jul 04 13:35:32 NZST 2021
     */
    int insertSelective(CheckRound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_round
     *
     * @mbg.generated Sun Jul 04 13:35:32 NZST 2021
     */
    CheckRound selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_round
     *
     * @mbg.generated Sun Jul 04 13:35:32 NZST 2021
     */
    int updateByPrimaryKeySelective(CheckRound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_round
     *
     * @mbg.generated Sun Jul 04 13:35:32 NZST 2021
     */
    int updateByPrimaryKey(CheckRound record);
    CheckRound selectByName(@Param("projectId") Long projectId, @Param("taskId") Long taskId, @Param("roundName") String roundName, @Param("notThisId") Long notThisId);
    Page<CheckRound> selectPaged(Map<String, Object> criteria);
}