package com.cit.dmt.core.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cit.dmt.core.model.Country;
import com.github.pagehelper.Page;

public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int insertSelective(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    Country selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int updateByPrimaryKeySelective(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int updateByPrimaryKey(Country record);

    Country selectByCode(@Param("countryCode") String countryCode, @Param("notThisId") Long notThisId);
    Country selectByName(@Param("countryName") String countryName, @Param("notThisId") Long notThisId);
	Page<Country> selectPaged(Map<String, Object> criteria);
	List<Country> selectHaveCt(@Param("status") String status);
}