package com.cit.dmt.core.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cit.dmt.core.model.CountryLanguage;
import com.github.pagehelper.Page;

public interface CountryLanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country_language
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country_language
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int insert(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country_language
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int insertSelective(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country_language
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    CountryLanguage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country_language
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int updateByPrimaryKeySelective(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country_language
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int updateByPrimaryKey(CountryLanguage record);
    
	Page<CountryLanguage> selectPaged(Map<String, Object> criteria);
    List<CountryLanguage> selectByCountryCode(String countryCode);
    CountryLanguage selectByCode(@Param("countryCode") String countryCode, @Param("languageCode") String languageCode);
    int deleteByCountryCode(String countryCode);
    int deleteByLanguageCode(String languageCode);
    int deleteByCode(@Param("countryCode") String countryCode, @Param("languageCode") String languageCode);
}