package com.cit.dmt.core.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cit.dmt.core.model.CtRoman;
import com.github.pagehelper.Page;

public interface CtRomanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_roman
     *
     * @mbg.generated Mon Feb 15 21:20:58 NZDT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_roman
     *
     * @mbg.generated Mon Feb 15 21:20:58 NZDT 2021
     */
    int insert(CtRoman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_roman
     *
     * @mbg.generated Mon Feb 15 21:20:58 NZDT 2021
     */
    int insertSelective(CtRoman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_roman
     *
     * @mbg.generated Mon Feb 15 21:20:58 NZDT 2021
     */
    CtRoman selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_roman
     *
     * @mbg.generated Mon Feb 15 21:20:58 NZDT 2021
     */
    int updateByPrimaryKeySelective(CtRoman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_roman
     *
     * @mbg.generated Mon Feb 15 21:20:58 NZDT 2021
     */
    int updateByPrimaryKey(CtRoman record);
    
	Page<CtRoman> selectPaged(Map<String, Object> criteria);
	int insertBatch(List<CtRoman> ctRomans);
	int deleteBatch(@Param("countryCode") String countryCode, @Param("languageCode") String languageCode);
}