package com.cit.dmt.core.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cit.dmt.core.model.CtTransliteration;
import com.github.pagehelper.Page;

public interface CtTransliterationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_transliteration
     *
     * @mbg.generated Mon Feb 15 21:20:58 NZDT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_transliteration
     *
     * @mbg.generated Mon Feb 15 21:20:58 NZDT 2021
     */
    int insert(CtTransliteration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_transliteration
     *
     * @mbg.generated Mon Feb 15 21:20:58 NZDT 2021
     */
    int insertSelective(CtTransliteration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_transliteration
     *
     * @mbg.generated Mon Feb 15 21:20:58 NZDT 2021
     */
    CtTransliteration selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_transliteration
     *
     * @mbg.generated Mon Feb 15 21:20:58 NZDT 2021
     */
    int updateByPrimaryKeySelective(CtTransliteration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_transliteration
     *
     * @mbg.generated Mon Feb 15 21:20:58 NZDT 2021
     */
    int updateByPrimaryKey(CtTransliteration record);
    
	Page<CtTransliteration> selectPaged(Map<String, Object> criteria);
	int insertBatch(List<CtTransliteration> ctTransliterations);
	int deleteBatch(@Param("countryCode") String countryCode, @Param("languageCode") String languageCode);
}