package com.cit.dmt.core.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cit.dmt.core.model.Language;
import com.github.pagehelper.Page;

public interface LanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int insert(Language record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int insertSelective(Language record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    Language selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int updateByPrimaryKeySelective(Language record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sun Feb 07 21:08:55 NZDT 2021
     */
    int updateByPrimaryKey(Language record);

    Language selectByCode(@Param("languageCode") String languageCode, @Param("notThisId") Long notThisId);
    Language selectByName(@Param("languageName") String languageName, @Param("notThisId") Long notThisId);
	Page<Language> selectPaged(Map<String, Object> criteria);
	List<Language> selectByCountry(@Param("countryCode") String countryCode, @Param("status") String status);
}