package com.cit.dmt.core.dao;

import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cit.dmt.core.model.SysFun;
import com.github.pagehelper.Page;

public interface SysFunMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fun
     *
     * @mbg.generated Mon Jan 18 20:26:22 NZDT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fun
     *
     * @mbg.generated Mon Jan 18 20:26:22 NZDT 2021
     */
    int insert(SysFun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fun
     *
     * @mbg.generated Mon Jan 18 20:26:22 NZDT 2021
     */
    int insertSelective(SysFun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fun
     *
     * @mbg.generated Mon Jan 18 20:26:22 NZDT 2021
     */
    SysFun selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fun
     *
     * @mbg.generated Mon Jan 18 20:26:22 NZDT 2021
     */
    int updateByPrimaryKeySelective(SysFun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fun
     *
     * @mbg.generated Mon Jan 18 20:26:22 NZDT 2021
     */
    int updateByPrimaryKey(SysFun record);

    SysFun selectByFunNo(@Param("funNo") String funNo, @Param("notThisId") Long notThisId);
	Page<SysFun> selectPaged(Map<String, Object> criteria);
	int deleteByPageName(String pageName);
}