package com.cit.dmt.core.dao;

import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cit.dmt.core.model.Task;
import com.github.pagehelper.Page;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Thu Feb 25 21:10:27 NZDT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Thu Feb 25 21:10:27 NZDT 2021
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Thu Feb 25 21:10:27 NZDT 2021
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Thu Feb 25 21:10:27 NZDT 2021
     */
    Task selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Thu Feb 25 21:10:27 NZDT 2021
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Thu Feb 25 21:10:27 NZDT 2021
     */
    int updateByPrimaryKey(Task record);
    
    Task selectByName(@Param("projectId") Long projectId, @Param("taskName") String taskName, @Param("notThisId") Long notThisId);
	Page<Task> selectPaged(Map<String, Object> criteria);
}